services:
  springbootTestService:
    image: pattanimrankhan/springapp:latest
    container_name: springbootTest
    ports:
    - 8080:8080
    env_file:
    - ~/springtest_var.env
    networks:
    - springbootmongo
    depends_on:
    - mongodbTest

  mongodbTest:
    image: mongo:latest
    container_name: mongoTestDB
    env_file:
    - /tmp/mongo_var.env
    networks:
    - springbootmongo
    volumes:
    - ebsvol
volumes:
  ebsvol:
    driver: local

networks:
  springbootmongo:
    driver: bridge
