services:
  springservicetest:
    image: pattanimrankhan/springapp:latest
    container_name: springboottest
    ports:
    - 8080:8080
    env_file:
    - /tmp/spring_var.env
    networks:
    - springappmongo
    depends_on:
    - mongodbtest

  mongodbtest:
    image: mongo:latest
    container_name: mongodb
    env_file:
    - /tmp/mongo_var.env
    networks:
    - springappmongo
    volumes:
    - ebsvol
volumes:
  ebsvol:
    driver: local

networks:
  springappmongo:
    driver: bridge
